### YamlMime:PythonClass
uid: azure.identity.aio.SharedTokenCacheCredential
name: SharedTokenCacheCredential
fullName: azure.identity.aio.SharedTokenCacheCredential
module: azure.identity.aio
inheritances:
- azure.identity._internal.shared_token_cache.SharedTokenCacheBase
- azure.identity.aio._internal.AsyncContextManager
summary: Authenticates using tokens in the local cache shared between Microsoft applications.
constructor:
  syntax: SharedTokenCacheCredential(username=None, **kwargs)
  parameters:
  - name: username
    description: 'Username (typically an email address) of the user to authenticate
      as. This is required because the local cache

      may contain tokens for multiple identities.'
    isRequired: true
    types:
    - <xref:str>
methods:
- uid: azure.identity.aio.SharedTokenCacheCredential.close
  name: close
  summary: Close the credential's transport session.
  signature: close()
- uid: azure.identity.aio.SharedTokenCacheCredential.get_token
  name: get_token
  summary: 'Get an access token for *scopes* from the shared cache.


    If no access token is cached, attempt to acquire one using a cached refresh token.


    This method is called automatically by Azure SDK clients.'
  signature: 'get_token(*scopes: str, **kwargs: typing.Any) -> AccessToken'
  parameters:
  - name: scopes
    description: desired scopes for the access token. This method requires at least
      one scope.
    isRequired: true
    types:
    - <xref:str>
  return:
    types:
    - <xref:azure.core.credentials.AccessToken>
  exceptions:
  - "type: f:azure.identity.CredentialUnavailableError> \u2013 the cache is unavailabl"
  - "type: ns insufficient user information * <xref:azure.core.exceptions.ClientAuthenticationError>\
    \ \u2013 authentication failed. The error's `message` attribute gives a reason.\
    \ Any error response from Azure Active Directory is available as the error's `response`\
    \ attribute"
