### YamlMime:PythonClass
uid: azure.servicefabric.models.ValidationFailedChaosEvent
name: ValidationFailedChaosEvent
fullName: azure.servicefabric.models.ValidationFailedChaosEvent
module: azure.servicefabric.models
inheritances:
- azure.servicefabric.models._models_py3.ChaosEvent
summary: 'Chaos event corresponding to a failure during validation.


  All required parameters must be populated in order to send to Azure.'
constructor:
  syntax: 'ValidationFailedChaosEvent(*, time_stamp_utc, reason: Optional[str] = None,
    **kwargs) -> None'
  parameters:
  - name: time_stamp_utc
    description: 'Required. The UTC timestamp when this Chaos event

      was generated.'
    types:
    - <xref:azure.servicefabric.models.datetime>
  - name: kind
    description: Required. Constant filled by server.
    types:
    - '[str](https://docs.python.org/3.6/library/stdtypes.html#str)'
  - name: reason
    description: 'Describes why the ValidationFailedChaosEvent was generated.

      This may happen because more than MaxPercentUnhealthyNodes are unhealthy

      for more than MaxClusterStabilizationTimeout. This reason will be in the

      Reason property of the ValidationFailedChaosEvent as a string.'
    types:
    - '[str](https://docs.python.org/3.6/library/stdtypes.html#str)'
